services:
  fastapi-app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code  
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password  
      MYSQL_DATABASE: my_db
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql 

volumes:
  mysql-data:
