services:
  fastapi-app: 
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code

# Volúmenes no son necesarios si no tienes MySQL
# volumes:
#   mysql-data:  # Puedes eliminar esta parte si ya no estás usando MySQL
